# 컬럼 관리 설정 파일
config:
  author: ColumnManager
  description: 컬럼 관리 설정 파일
  version: '1.0'

# 살릴 컬럼들 (FS.csv의 모든 컬럼)
keep_columns:
# 기본 컬럼 정보
- 회사명
- 거래소코드
- 회계년도
- default

- 순금융비용이자보상배율
- 사내유보율
- 재고자산증가율
- 총자본회전률
- 총자산수익률
- 비유동자산구성비율
- 기업순이익률
- 경영자본영업이익률
- 총자본영업이익률
- 총자본사업이익률
- 유동자산구성비율
- 순운전자본회전률
- 총자본투자효율
- 경영자본순이익률
- 차입금의존도
- 이자보상배율
- 유동비율



# market value 컬럼
- 주당순이익


# 죽일 컬럼들 (필요에 따라 편집)
drop_columns:
- 총자산
- 총부채
- 총자본
- 발행주식총수
- 유동자산
- 유동부채
- 매출액
- 자본금
- 이익잉여금
- 영업이익
- 당기순이익
- 영업현금흐름
- 매출액증가율
- 매출액총이익률
- 매출액영업이익률
- 매출액순이익률
- 자기자본순이익률
- 부채비율
- 총자본증가율
- 유형자산증가율
- 비유동생물자산증가율
- 투자부동산증가율
- 비유동자산증가율
- 유동자산증가율
- 자기자본증가율
- 영업이익증가율
- 순이익증가율
- 총포괄이익증가율
- 종업원당부가가치증가율
- 종업원수증가율
- 종업원당매출액증가율
- 종업원당인건비증가율
- 자기자본영업이익률
- 경영자본영업이익률
- 자본금영업이익률
- 자본금순이익률
- 매출원가율
- 영업비용률
- 기타손익비율
- 금융손익비율
- 금융비용부담률
- 외환이익비율
- 광고선전비비율
- 세금과공과비율
- 기업순이익률
- 수지비율
- 인건비비율
- R&D투자효율
- 세금과공과총비용비율
- 금융비용총비용비율
- 감가상각비총비용비율
- 감가상각률
- 누적감가상각률
- 이자부담률
- 지급이자율
- 차입금평균이자율
- 유보율
- 사내유보자기자본비율
- 적립금비율
- 평균배당률
- 자기자본배당률
- 배당성향
- 주당매출액
- 주당현금흐름
- 주당순자산
- 주당영업이익
- 재고자산유동자산비율
- 유동비유동자산비율
- 당좌자산구성비율
- 자기자본구성비율
- 타인자본구성비율
- 자기자본배율
- 비유동비율
- 비유동장기적합률
- 당좌비율
- 현금비율
- 매출채권비율
- 재고자산순운전자본비율
- 매출채권매입채무비율
- 매출채권상제품비율
- 매입채무재고자산비율
- 유동부채비율
- 단기차입금총차입금비율
- 비유동부채비율
- 비유동부채순운전자본비율
- 순운전자본비율
- 차입금비율
- 유보액대비율
- 유보액납입자본비율
- 유동자산집중도
- 비유동자산집중도
- 투자집중도
- 현금흐름부채비율
- 현금흐름차입금비율
- 현금흐름총자본비율
- 현금흐름매출액비율
- 영업이익이자보상배율
- 경영자본회전률
- 자기자본회전률
- 자본금회전률
- 타인자본회전률
- 매입채무회전률
- 매입채무회전기간
- 유동자산회전률
- 당좌자산회전률
- 재고자산회전률
- 재고자산회전기간
- 상품제품회전률
- 원부재료회전률
- 재공품회전률
- 매출채권회전률
- 매출채권회전기간
- 비유동자산회전률
- 유형자산회전률
- 운전자본회전률
- 회전기간
- 부가가치
- 종업원당부가가치
- 종업원당매출액
- 종업원당영업이익
- 종업원당순이익
- 종업원당인건비
- 노동장비율
- 기계장비율
- 자본집약도
- 설비투자효율
- 기계투자효율
- 부가가치율
- 노동소득분배율
- 자본분배율
- 이윤분배율
- 법인세비용차감전손익
- 인건비
- 금융비용
- 임차료
- 세금과공과
- 감가상각비
- 종업원수
- 기업가치
- EBITDA
- EV_EBITDA배수
- PER최고
- PER최저
- PBR최고
- PBR최저
- PCR최고
- PCR최저
- PSR최고
- PSR최저
- EBITDA매출액비율
- EBITDA금융비용배수
- 주당EBITDA