# 컬럼 관리 설정 파일
config:
  author: ColumnManager
  description: 컬럼 관리 설정 파일
  version: '1.0'

# 살릴 컬럼들 (FS.csv의 모든 컬럼)
keep_columns:
- 회사명,
- 거래소코드
- 연도
- default

# - 매출액증가율
# - 영업이익증가율
# - 당기순이익증가율
# - 총자산증가율
# - 총부채증가율
# - 영업현금흐름증가율
# - 부채자본비율
# - 자본비율
# - 이자부담차입금비율
# - 장기차입금자본비율
# - 총자산수익률(ROA)
# - 자기자본수익률(ROE)
# - 투하자본수익률(ROIC)
# - 총자산회전율
# - 영업이익대차입금비율
# - 현금흐름대부채비율
# - DOL
# - DFL
# - ΔDFL
# - 로그총자산
# - EV
# - EV/EBITDA
# - PBR
# - PER
# - PSR
# - PCR
# - 주식회전율
# - ROA_변화량
# - ROE_변화량
# - ROIC_변화량
# - Δ부채자본비율
# - Δ자본비율
# - Δ총자산회전율
# - Δ현금흐름대부채비율
# - 납입자본금

- 매출액증가율
- 총자산증가율
- 자본비율
- 이자부담차입금비율
- 총자산수익률(ROA)
- 투하자본수익률(ROIC)
- 영업이익대차입금비율
- 현금흐름대부채비율
- 로그총자산
- EV
- PCR
- PER
- Δ부채자본비율
- Δ자본비율
- ROIC_변화량
- 납입자본금
- Δ총자산회전율




# 죽일 컬럼들 (필요에 따라 편집)
drop_columns:
- 총자산
- 유형자산
- 무형자산
- 재고자산
- 현금및현금성자산
- 비유동자산
- 총자본
- 발행주식총수
- 총부채
- 유동부채
- 비유동부채
- 장기차입금
- 단기차입금
- 매출채권
- 매입채무
- 선수수익
- 기타유동부채
- 기타유동자산
- (금융)리스부채
- 단기금융상품(금융기관예치금)
- 자본금
- 기타포괄손익누계액
- 매출액
- 매출원가
- 매출총이익
- 영업이익
- 계속영업이익
- 당기순이익
- 이자비용
- 영업현금흐름
- 종가
- 거래량
- 상장주식수
- 시가총액
- avg_총자산
- avg_유형자산
- avg_무형자산
- avg_재고자산
- avg_현금및현금성자산
- avg_비유동자산
- avg_총자본
- avg_발행주식총수
- avg_총부채
- avg_유동부채
- avg_비유동부채
- avg_장기차입금
- avg_단기차입금
- avg_매출채권
- avg_매입채무
- avg_선수수익
- avg_기타유동부채
- avg_기타유동자산
- avg_(금융)리스부채
- avg_단기금융상품(금융기관예치금)
- avg_자본금
- avg_기타포괄손익누계액

- 영업운전자본
- 투하자본
- 경영자본
- avg_투하자본
- avg_경영자본
- avg_영업운전자본
- 로그시가총액
- 부채자산비율
- Δ부채자산비율
- 부채총자본비율


- 영업이익증가율
- 당기순이익증가율
- 영업현금흐름증가율
- 부채자본비율
- 장기차입금자본비율
- DOL
- ΔDFL
- EV/EBITDA
- PBR
- 주식회전율

- Δ현금흐름대부채비율
- DFL
- 총부채증가율
- 자기자본수익률(ROE)
- PSR
- ROA_변화량
- ROE_변화량
- 총자산회전율
