# 모델링 파이프라인 설정 파일
# ===================================

# 실험 정보
experiment:
  name: "default_modeling_run"
  version: "1.0.0"
  description: "한국 기업 부실예측 모델링 파이프라인"

# 로깅 설정
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  save_to_file: true

# 데이터 설정
data:
  input_path: "data/final"  # 전처리된 데이터가 있는 디렉토리
  files:
    X_train: "X_train.csv"
    X_val: "X_val.csv"  
    X_test: "X_test.csv"
    y_train: "y_train.csv"
    y_val: "y_val.csv"
    y_test: "y_test.csv"

# 샘플링 전략 설정
sampling:
  data_types:
    normal:
      enabled: true
      description: "원본 데이터 (샘플링 없음)"
    
    smote:
      enabled: true
      description: "BorderlineSMOTE 오버샘플링"
      sampling_strategy: 0.3  # 부실 클래스 비율 목표
      k_neighbors: 5
      m_neighbors: 10
    
    undersampling:
      enabled: false
      description: "언더샘플링"
      method: "random"  # random, edited_nearest_neighbours, tomek
      sampling_strategy: 0.5  # 정상 클래스 유지 비율
    
    combined:
      enabled: false
      description: "SMOTE + 언더샘플링 조합"
      smote_ratio: 0.3
      undersampling_ratio: 0.5

# 스케일링 설정
scaling:
  enabled: true
  column_groups:
    Standard:  # 표준 스케일링 적용할 컬럼명들 (정규분포에 가까운 변수들)
      - "총자산"
      - "총부채" 
      - "총자본"
      - "유동자산"
      - "유동부채"
      - "매출액"
      - "자본금"
      - "이익잉여금"
      - "영업이익"
      - "당기순이익"
      - "영업현금흐름"
      - "부가가치"
      - "인건비"
      - "금융비용"
      - "세금과공과"
      - "감가상각비"
      - "EBITDA"
      - "기업가치"
      - "종업원수"
      - "발행주식총수"
      - "법인세비용차감전손익"
      - "임차료"
      - "주당매출액"
      - "주당순이익"
      - "주당현금흐름"
      - "주당순자산"
      - "주당영업이익"
      - "주당EBITDA"
      - "종업원당부가가치"
      - "종업원당매출액"
      - "종업원당영업이익"
      - "종업원당순이익"
      - "종업원당인건비"
    
    Robust:  # 로버스트 스케일링 적용할 컬럼명들 (이상치에 강함, 비율/배수 변수들)
      - "매출액증가율"
      - "총자본증가율"
      - "유형자산증가율"
      - "비유동생물자산증가율"
      - "투자부동산증가율"
      - "비유동자산증가율"
      - "유동자산증가율"
      - "재고자산증가율"
      - "자기자본증가율"
      - "영업이익증가율"
      - "순이익증가율"
      - "총포괄이익증가율"
      - "종업원당부가가치증가율"
      - "종업원수증가율"
      - "종업원당매출액증가율"
      - "종업원당인건비증가율"
      - "이자보상배율"
      - "부채비율"
      - "자기자본배율"
      - "이자부담률"
      - "지급이자율"
      - "차입금평균이자율"
      - "배당성향"
      - "평균배당률"
      - "자기자본배당률"
      - "영업이익이자보상배율"
      - "순금융비용이자보상배율"
      - "EV_EBITDA배수"
      - "PER최고"
      - "PER최저"
      - "PBR최고"
      - "PBR최저"
      - "PCR최고"
      - "PCR최저"
      - "PSR최고"
      - "PSR최저"
      - "EBITDA금융비용배수"
      - "매입채무회전률"
      - "유동자산회전률"
      - "당좌자산회전률"
      - "재고자산회전률"
      - "상품제품회전률"
      - "원부재료회전률"
      - "재공품회전률"
      - "매출채권회전률"
      - "비유동자산회전률"
      - "유형자산회전률"
      - "순운전자본회전률"
      - "운전자본회전률"
      - "총자본회전률"
      - "경영자본회전률"
      - "자기자본회전률"
      - "자본금회전률"
      - "타인자본회전률"
      - "매입채무회전기간"
      - "재고자산회전기간"
      - "매출채권회전기간"
      - "회전기간"
      - "R&D투자효율"
      - "총자본투자효율"
      - "설비투자효율"
      - "기계투자효율"
      - "노동장비율"
      - "기계장비율"
      - "자본집약도"
    
    MinMax:  # 최소-최대 스케일링 적용할 컬럼명들 (비율 변수들, 0-1 범위로 제한)
      - "매출액총이익률"
      - "매출액영업이익률"
      - "매출액순이익률"
      - "총자산수익률"
      - "자기자본순이익률"
      - "총자본사업이익률"
      - "총자본영업이익률"
      - "자기자본영업이익률"
      - "경영자본영업이익률"
      - "경영자본순이익률"
      - "자본금영업이익률"
      - "자본금순이익률"
      - "매출원가율"
      - "영업비용률"
      - "기타손익비율"
      - "금융손익비율"
      - "금융비용부담률"
      - "외환이익비율"
      - "광고선전비비율"
      - "세금과공과비율"
      - "기업순이익률"
      - "수지비율"
      - "인건비비율"
      - "세금과공과총비용비율"
      - "금융비용총비용비율"
      - "감가상각비총비용비율"
      - "감가상각률"
      - "누적감가상각률"
      - "유보율"
      - "사내유보율"
      - "사내유보자기자본비율"
      - "적립금비율"
      - "유동비율"
      - "당좌비율"
      - "현금비율"
      - "유동자산구성비율"
      - "재고자산유동자산비율"
      - "유동비유동자산비율"
      - "당좌자산구성비율"
      - "비유동자산구성비율"
      - "자기자본구성비율"
      - "타인자본구성비율"
      - "비유동비율"
      - "비유동장기적합률"
      - "매출채권비율"
      - "재고자산순운전자본비율"
      - "매출채권매입채무비율"
      - "매출채권상제품비율"
      - "매입채무재고자산비율"
      - "유동부채비율"
      - "단기차입금총차입금비율"
      - "비유동부채비율"
      - "비유동부채순운전자본비율"
      - "순운전자본비율"
      - "차입금의존도"
      - "차입금비율"
      - "유보액대비율"
      - "유보액납입자본비율"
      - "유동자산집중도"
      - "비유동자산집중도"
      - "투자집중도"
      - "현금흐름부채비율"
      - "현금흐름차입금비율"
      - "현금흐름총자본비율"
      - "현금흐름매출액비율"
      - "부가가치율"
      - "노동소득분배율"
      - "자본분배율"
      - "이윤분배율"
      - "EBITDA매출액비율"

# 특성 선택 설정
feature_selection:
  enabled: true
  lasso:
    alphas: [0.001, 0.01, 0.1, 1.0, 10.0, 100.0]
    cv_folds: 5
    threshold: "median"  # median, mean, 또는 숫자값

# 모델 설정
models:
  logistic_regression:
    enabled: true
    penalty: ["l1", "l2", "elasticnet"]
    l2_solvers: ["lbfgs", "liblinear", "newton-cg", "sag", "saga"]
    C_range: [0.001, 100.0]  # log scale
    max_iter_range: [100, 1000]
    l1_ratio_range: [0.1, 0.9]  # elasticnet용
    n_trials: 50
  
  random_forest:
    enabled: true
    n_estimators_range: [50, 300]
    max_depth_range: [3, 20]
    min_samples_split_range: [2, 20]
    min_samples_leaf_range: [1, 10]
    max_features_range: [0.1, 1.0]
    n_trials: 50
  
  xgboost:
    enabled: true
    n_estimators_range: [50, 300]
    max_depth_range: [3, 10]
    learning_rate_range: [0.01, 0.3]
    subsample_range: [0.6, 1.0]
    colsample_bytree_range: [0.6, 1.0]
    reg_alpha_range: [0.0, 10.0]
    reg_lambda_range: [1.0, 10.0]
    n_trials: 50

# Threshold 최적화 설정
threshold_optimization:
  enabled: true
  metric_priority: "f1"  # f1, precision, recall, balanced_accuracy

# 앙상블 설정
ensemble:
  enabled: true
  method: "weighted_average"  # simple_average, weighted_average, stacking
  auto_weight: true  # 검증 성능 기반 자동 가중치
  models: ["logistic_regression", "random_forest", "xgboost"]
  data_types: ["normal", "smote"]
  threshold_optimization:
    enabled: true
    metric_priority: "f1"

# 출력 설정
output:
  base_dir: "outputs/modeling_runs"
  save_models: true
  save_results: true
  generate_visualizations: true
  report_format: ["txt", "html"]

# 성능 설정
performance:
  n_jobs: 1  # 병렬 처리 코어 수 (-1: 모든 코어)

# 랜덤 시드
random_state: 42