cv_folds: 3
data:
  files:
    X_test: X_test.csv
    X_train: X_train.csv
    X_val: X_val.csv
    y_test: y_test.csv
    y_train: y_train.csv
    y_val: y_val.csv
  input_path: data/final
ensemble:
  auto_weight: true
  data_types:
  - normal
  - smote
  - undersampling
  - combined
  enabled: false
  method: weighted_average
  models:
  - logistic_regression
  - random_forest
  - xgboost
  threshold_optimization:
    enabled: true
    metric_priority: f1
  weight_metric: average_precision
experiment:
  description: 한국 기업 부실예측 모델링 파이프라인
  name: quick_test_full_pipeline
  version: 1.0.0
feature_selection:
  enabled: false
  lasso_cv:
    alphas:
    - 0.001
    - 0.01
    - 0.1
    - 1.0
    - 10.0
    - 100.0
    threshold: median
  logistic_regression_cv:
    Cs:
    - 0.01
    - 0.1
    - 1.0
    - 10.0
    max_iter: 10000
    penalty: l1
    scoring: f1
    solver: saga
    threshold: median
  method: logistic_regression_cv
  permutation_importance:
    base_estimator: random_forest
    estimator_params:
      logistic_regression:
        C: 1.0
        class_weight: balanced
        max_iter: 1000
        penalty: l2
        solver: lbfgs
      random_forest:
        class_weight: balanced
        max_depth: 10
        min_samples_leaf: 2
        min_samples_split: 5
        n_estimators: 100
      xgboost:
        colsample_bytree: 0.8
        learning_rate: 0.1
        max_depth: 6
        n_estimators: 100
        subsample: 0.8
    max_features: null
    n_repeats: 5
    random_state: 42
    scoring: f1
    threshold: median
  shap:
    base_estimator: random_forest
    estimator_params:
      logistic_regression:
        C: 1.0
        class_weight: balanced
        max_iter: 1000
        penalty: l2
        solver: lbfgs
      random_forest:
        class_weight: balanced
        max_depth: 8
        min_samples_leaf: 3
        min_samples_split: 5
        n_estimators: 100
      xgboost:
        colsample_bytree: 0.8
        learning_rate: 0.1
        max_depth: 6
        n_estimators: 100
        subsample: 0.8
    explainer_type: tree
    max_features: 10
    sample_size: 5000
    threshold: median
logging:
  level: INFO
  save_to_file: true
models:
  logistic_regression:
    C_range:
    - 0.01
    - 100
    class_weight: balanced
    enabled: true
    l1_ratio_range:
    - 0.1
    - 0.9
    l2_solvers:
    - newton-cg
    - lbfgs
    - saga
    - liblinear
    max_iter_range:
    - 100
    - 10000
    n_trials: 20
    penalty:
    - l2
  optimization:
    description: 하이퍼파라미터 최적화 시 사용할 주요 메트릭
    primary_metric: f1
  random_forest:
    class_weight: balanced
    enabled: true
    max_depth_range:
    - 3
    - 20
    max_features_range:
    - 0.1
    - 1.0
    min_samples_leaf_range:
    - 1
    - 10
    min_samples_split_range:
    - 2
    - 20
    n_estimators_range:
    - 100
    - 300
    n_trials: 20
  xgboost:
    class_weight_mode: scale_pos_weight
    colsample_bytree_range:
    - 0.6
    - 1.0
    enabled: true
    learning_rate_range:
    - 0.005
    - 0.3
    max_depth_range:
    - 3
    - 10
    n_estimators_range:
    - 100
    - 300
    n_trials: 20
    reg_alpha_range:
    - 0.0
    - 10.0
    reg_lambda_range:
    - 1.0
    - 10.0
    scale_pos_weight: auto
    subsample_range:
    - 0.6
    - 1.0
output:
  base_dir: outputs/modeling_runs
  generate_visualizations: true
  report_format:
  - txt
  - html
  save_models: true
  save_results: true
performance:
  n_jobs: -1
random_state: 42
sampling:
  data_types:
    combined:
      description: SMOTE + 언더샘플링 조합
      enabled: false
      smote:
        k_neighbors: 5
        kind: borderline-1
        m_neighbors: 10
        sampling_strategy: 0.5
      undersampling:
        method: tomek
        random_state: 42
        sampling_strategy: 1
    ctgan:
      ctgan:
        batch_size: 500
        discriminator_dim:
        - 256
        - 256
        epochs: 50
        generator_dim:
        - 256
        - 256
      description: CTGAN 기반 synthetic 데이터 생성
      enabled: false
      sampling_strategy: 0.1
    normal:
      description: 원본 데이터 (샘플링 없음)
      enabled: true
    smote:
      description: BorderlineSMOTE 오버샘플링
      enabled: false
      k_neighbors: 5
      kind: borderline-1
      m_neighbors: 10
      random_state: 42
      sampling_strategy: 1
    undersampling:
      description: 언더샘플링
      enabled: false
      method: tomek
      random_state: 42
      sampling_strategy: 1
scaling:
  column_groups:
    log: null
    minmax: null
    robust:
    - 매출액증가율
    - 영업이익증가율
    - 당기순이익증가율
    - 총자산증가율
    - 총부채증가율
    - 영업현금흐름증가율
    - 부채자본비율
    - 자본비율
    - 이자부담차입금비율
    - 장기차입금자본비율
    - 총자산수익률(ROA)
    - 자기자본수익률(ROE)
    - 투하자본수익률(ROIC)
    - 총자산회전율
    - 영업이익대차입금비율
    - 현금흐름대부채비율
    - DOL
    - DFL
    - ΔDFL
    - 로그총자산
    - EV
    - EV/EBIT
    - PBR
    - PER
    - PSR
    - PCR
    - 주식회전율
    - ROA_변화량
    - ROE_변화량
    - ROIC_변화량
    - Δ부채자본비율
    - Δ자본비율
    - Δ총자산회전율
    - Δ현금흐름대부채비율
    - 납입자본금
    standard: null
  enabled: false
threshold_optimization:
  enabled: true
  metric_priority: f1
  search_range:
    high: 0.5
    low: 0.0005
    n_grid: 500
validation:
  logistic_holdout:
    n_iterations: 30
    test_size: 0.2
  method: logistic_holdout
  nested_cv:
    inner_folds: 3
    n_trials: 50
    outer_folds: 5
